### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jonchoi** [omise/omise-go#22]
Hi, is there a plan to have more documentation on how to begin contributing? Noticed there isn't a "getting started" page in terms of reading code or list of issues etc. Thanks!

**Comment by iporsut** [comment]
Hi @jon-choi thank you for your interesting to contribute. For the beginning you can fork this repository and commit changed then open pull request. Our team will review your changed, If it's ok we will merge PR to master branch.

**Comment by jon-choi** [comment]
Makes sense, but was just wondering if there was an overall roadmap that people can be contributing to rather than making blind guesses on what's needed.

**Comment by chakrit** [comment]
@jonchoi Hey Jon, sorry for the delay. We don't have a public ROADMAP for that yet, but I think generally you can look for new APIs being released on omise.co/docs but not yet available via the GO bindings.

There are also several things that could be improved, for example:
* This project uses a code generator internally, there are rooms for refactoring/improvements/simplification in the generator itself.
* The operations package is very large, if there is a way to reduce the number of files smartly that'd be nice.

Also documentation improvements and bugfixes are more than welcome.

**Comment by chakrit** [comment]
Going to close this issue for now, feel free to open a new one if there are issues.
