### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by requiem202** [omise/omise-go#48]
Hi.

As the title said, is this package still being actively maintained? It seems to lack behind in compatibility with Omise API documentation.

**Comment by maetad** [comment]
I think they already move to https://github.com/opn-ooo/omise-go
but in the repo, I see `import github.com/omise/omise-go/internal`.

that means we can't use it 😂

**Comment by danfowler** [comment]
This package is still being maintained. Currently reviewing old issues and pull requests with an aim to support more active maintenance in the upcoming months.
