### ISSUE TITLE
Refactor generator template use bytes.Buffer default value.

### ISSUE THREAD

**Issue by iporsut** [omise/omise-go#9]
I found in `internal/generator/gen_list_job.tmpl` and `internal/generator/gen_search_job.tmpl` use buf with type pointer of bytes.Buffer.

I think we can use only value of bytes.Buffer with zero value like this.

`var buf bytes.Buffer`

**Comment by wingyplus** [comment]
Is this issue still valid?

**Comment by iporsut** [comment]
@wingyplus We changed method to generate that type. Sorry I forgot to close this issue.
